### ISSUE TITLE
How to change Grid size?

### ISSUE THREAD

**Issue by Acrobyux** [Kortaggio/battleboat#7]
I already changed Grid size to 5x5 successfully, but the AI doesn't seems to place ships correctly in the new player's grid and either on computer's grid because I missed all shoots.
![image](https://user-images.githubusercontent.com/33229973/32876981-d847aa9a-ca64-11e7-9994-cfc63595b359.png)

**Comment by billmei** [comment]
Ah, it seems like there is a bug in the placement logic here:

https://github.com/billmei/battleboat/blob/4beafba45d412a6a9ad5dcfe13623e559bf2ef23/js/battleboat.js#L692-L693

Instead of hardcoding `10*Math.random()` it should be `Game.size*Math.random()`

I pushed a change which should fix this. a9e1716

Feel free to reopen the issue if the fix doesn't work.

**Comment by Acrobyux** [comment]
It works fine with 10 x 10 and over, proved with  15 x 15 and 20 x 20 too, but when it gets 9 x 9 or lower (proved till 5 x 5) this doesn't seem to work for the AI shooting to player's grid.
- THIS example is with 9x9 Grid, I was able to attack computer's grid and win because AI can't attack player's Grid on 9x9 and under.
![image](https://user-images.githubusercontent.com/33229973/33003654-ad84c552-cd81-11e7-9f33-740b49e722d5.png)
